### ISSUE TITLE
在watch和methods您是如何权衡这两个方法之间的界限的呢。

### ISSUE THREAD

**Issue by lidazhao** [hzzly/vue-particle-line#1]
在canvas的的静态运用，让人眼前一亮，是个十分好的canvas和vue结合的例子。
在项目中很少看到您使用watch，您是如何判断何时使用methods而不是watch.感谢。

**Comment by hzzly** [comment]
当时写这个的时候vue还没玩的好，所以多数用的methods。watch是用来响应数据的变化，当data或state中的数据变化时可以用watch来监听。mtehods是用来处理某种事件或动作。
